using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEditor.U2D.Sprites;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.U2D;
using UnityEngine.U2D.Animation;

// Builds the v012 rig from Assets/EstelleV12/rig.json and anim.json, generated by
// references/3_parts/v012/rig_v8.py and anim_v8.py. v012 separates the base body from the
// clothing layers (Spine-style); every layer sits in place in the reference pixel space and
// shares one skeleton, and each layer follows one motion chain only.
public static class EstelleV12Build
{
    const string Root = "Assets/EstelleV12";
    const string Art = Root + "/Art/";
    const string PrefabPath = Root + "/EstelleV12Rig.prefab";
    const string ScenePath = Root + "/EstelleV12Directions.unity";
    const float FlashWorldSize = 0.72f;

    [Serializable] class RigBone { public string name; public string parent; public float x; public float y; }
    [Serializable] class SkinBone { public string name; public int parent; public float x; public float y; }
    [Serializable] class RigPart
    {
        public string name; public string file; public int width; public int height; public int order;
        public float ppu; public string anchor; public float pivotX; public float pivotY;
        public SkinBone[] bones; public float[] vertices; public int[] indices; public int[] edges; public float[] weights;
    }
    [Serializable] class Rig { public float refPpu; public float groundY; public float originX; public RigBone[] bones; public RigPart[] parts; }
    [Serializable] class Channel { public string bone; public string prop; public float[] times; public float[] values; public float[] tangents; }
    [Serializable] class Clip { public string name; public float length; public bool loop; public Channel[] channels; }
    [Serializable] class AnimData { public Clip[] clips; }

    static Rig rig;

    [MenuItem("Estelle V12/Build Rig")]
    public static void Build()
    {
        rig = JsonUtility.FromJson<Rig>(File.ReadAllText(Root + "/rig.json"));
        var anim = JsonUtility.FromJson<AnimData>(File.ReadAllText(Root + "/anim.json"));
        Directory.CreateDirectory(Root + "/Animation");
        AssetDatabase.Refresh();
        var sprites = new Dictionary<string, Sprite>();
        foreach (var part in rig.parts) sprites[part.name] = ImportPart(part);
        sprites["CastFlash"] = ImportPlain("v12-CastFlash.png", 256f / FlashWorldSize);
        var rigObject = MakeRig(sprites, out var restLocal);
        var clips = anim.clips.Select(c => MakeClip(c, rigObject, restLocal)).ToArray();
        var controller = MakeController(clips[0], clips[1]);
        rigObject.GetComponent<Animator>().runtimeAnimatorController = controller;
        var prefab = PrefabUtility.SaveAsPrefabAsset(rigObject, PrefabPath);
        UnityEngine.Object.DestroyImmediate(rigObject);
        MakeScene(prefab);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Validate(prefab);
        Debug.Log("ESTELLE_V12_BUILD_SUCCESS prefab=" + PrefabPath + " scene=" + ScenePath);
    }

    static Vector3 World(float x, float y) => new Vector3((x - rig.originX) / rig.refPpu, (rig.groundY - y) / rig.refPpu, 0);

    static TextureImporter BaseImport(string file, float ppu)
    {
        var importer = (TextureImporter)AssetImporter.GetAtPath(Art + file);
        if (importer == null) throw new Exception("Missing art " + file);
        importer.textureType = TextureImporterType.Sprite;
        importer.spriteImportMode = SpriteImportMode.Single;
        importer.spritePixelsPerUnit = ppu;
        importer.alphaIsTransparency = true;
        importer.mipmapEnabled = false;
        importer.maxTextureSize = 2048;
        importer.textureCompression = TextureImporterCompression.Uncompressed;
        importer.filterMode = FilterMode.Bilinear;
        importer.wrapMode = TextureWrapMode.Clamp;
        var settings = new TextureImporterSettings();
        importer.ReadTextureSettings(settings);
        settings.spriteMeshType = SpriteMeshType.Tight;
        importer.SetTextureSettings(settings);
        importer.SaveAndReimport();
        return importer;
    }

    static Sprite ImportPlain(string file, float ppu)
    {
        BaseImport(file, ppu);
        return AssetDatabase.LoadAssetAtPath<Sprite>(Art + file);
    }

    static Sprite ImportPart(RigPart part)
    {
        var importer = BaseImport(part.file, part.ppu);
        var factories = new SpriteDataProviderFactories(); factories.Init();
        var data = factories.GetSpriteEditorDataProviderFromObject(importer);
        data.InitSpriteEditorDataProvider();
        var rects = data.GetSpriteRects();
        if (rects.Length != 1) throw new Exception(part.name + " should be a single sprite.");
        rects[0].name = part.name;
        rects[0].alignment = SpriteAlignment.Custom;
        rects[0].pivot = new Vector2(part.pivotX, part.pivotY);
        data.SetSpriteRects(rects);
        data.Apply();
        if (part.bones != null && part.bones.Length > 0)
        {
            var id = rects[0].spriteID;
            var bones = part.bones.Select((b, i) => new SpriteBone {
                name = b.name, guid = GUID.Generate().ToString(), parentId = b.parent,
                position = new Vector3(b.x, b.y, 0), rotation = Quaternion.identity, length = 40f,
                color = Color.HSVToRGB((i * .618f) % 1f, .8f, 1f) }).ToList();
            data.GetDataProvider<ISpriteBoneDataProvider>().SetBones(id, bones);
            int count = part.vertices.Length / 2;
            var vertices = new Vertex2DMetaData[count];
            for (int v = 0; v < count; v++)
            {
                var w = part.weights;
                var bw = new BoneWeight {
                    boneIndex0 = (int)w[8 * v], weight0 = w[8 * v + 1], boneIndex1 = (int)w[8 * v + 2], weight1 = w[8 * v + 3],
                    boneIndex2 = (int)w[8 * v + 4], weight2 = w[8 * v + 5], boneIndex3 = (int)w[8 * v + 6], weight3 = w[8 * v + 7] };
                vertices[v] = new Vertex2DMetaData { position = new Vector2(part.vertices[2 * v], part.vertices[2 * v + 1]), boneWeight = bw };
            }
            var edges = new Vector2Int[part.edges.Length / 2];
            for (int e = 0; e < edges.Length; e++) edges[e] = new Vector2Int(part.edges[2 * e], part.edges[2 * e + 1]);
            var mesh = data.GetDataProvider<ISpriteMeshDataProvider>();
            mesh.SetVertices(id, vertices);
            mesh.SetIndices(id, part.indices);
            mesh.SetEdges(id, edges);
            data.Apply();
        }
        importer.SaveAndReimport();
        var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(Art + part.file);
        if (sprite == null) throw new Exception("Sprite failed to import: " + part.name);
        return sprite;
    }

    static GameObject SpriteObject(string name, Sprite sprite, Transform parent, Vector3 worldPosition, int order)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        go.transform.position = worldPosition;
        go.transform.rotation = Quaternion.identity;
        var renderer = go.AddComponent<SpriteRenderer>();
        renderer.sprite = sprite;
        renderer.sortingOrder = order;
        return go;
    }

    static GameObject MakeRig(Dictionary<string, Sprite> sprites, out Dictionary<Transform, Vector3> restLocal)
    {
        var root = new GameObject("EstelleV12Rig");
        root.AddComponent<SortingGroup>();
        var bones = new Dictionary<string, Transform>();
        var skeleton = new GameObject("Skeleton").transform;
        skeleton.SetParent(root.transform, false);
        foreach (var b in rig.bones)
        {
            var t = new GameObject(b.name).transform;
            t.SetParent(string.IsNullOrEmpty(b.parent) ? skeleton : bones[b.parent], false);
            t.position = World(b.x, b.y);
            t.localRotation = Quaternion.identity;
            bones[b.name] = t;
        }
        var layers = new GameObject("Layers").transform;
        layers.SetParent(root.transform, false);
        foreach (var part in rig.parts)
        {
            var anchor = bones[part.anchor];
            if (part.bones != null && part.bones.Length > 0)
            {
                var go = SpriteObject(part.name, sprites[part.name], layers, anchor.position, part.order);
                var skin = go.AddComponent<SpriteSkin>();
                skin.SetRootBone(bones[part.bones[0].name]);
                var state = skin.SetBoneTransforms(part.bones.Select(b => bones[b.name]).ToArray());
                skin.alwaysUpdate = true;
                skin.forceCpuDeformation = true;
                if (state.ToString() != "Ready") throw new Exception("Sprite Skin not ready: " + part.name + " " + state);
            }
            else
            {
                var go = SpriteObject(part.name, sprites[part.name], anchor, anchor.position, part.order);
                go.transform.localPosition = Vector3.zero;
            }
        }
        var flash = SpriteObject("CastFlash", sprites["CastFlash"], bones["StaffTip"], bones["StaffTip"].position, 70);
        flash.transform.localScale = new Vector3(0, 0, 1);
        flash.GetComponent<SpriteRenderer>().color = new Color(1, 1, 1, 0);
        restLocal = root.GetComponentsInChildren<Transform>(true).ToDictionary(t => t, t => t.localPosition);
        root.AddComponent<Animator>();
        return root;
    }

    static AnimationClip MakeClip(Clip data, GameObject rigObject, Dictionary<Transform, Vector3> rest)
    {
        string path = Root + "/Animation/" + data.name + ".anim";
        AssetDatabase.DeleteAsset(path);
        var clip = new AnimationClip { name = data.name, frameRate = 30 };
        var all = rigObject.GetComponentsInChildren<Transform>(true).ToDictionary(t => t.name);
        foreach (var ch in data.channels)
        {
            if (!all.TryGetValue(ch.bone, out var target)) throw new Exception("Unknown animated transform " + ch.bone);
            string tPath = AnimationUtility.CalculateTransformPath(target, rigObject.transform);
            if (ch.prop == "rot" && target.localRotation != Quaternion.identity)
                throw new Exception("Animated joint must rest at zero local rotation: " + ch.bone);
            void Set(Type type, string property, float offset)
            {
                var keys = new Keyframe[ch.times.Length];
                for (int k = 0; k < keys.Length; k++)
                    keys[k] = new Keyframe(ch.times[k], ch.values[k] + offset, ch.tangents[k], ch.tangents[k]);
                AnimationUtility.SetEditorCurve(clip, EditorCurveBinding.FloatCurve(tPath, type, property), new AnimationCurve(keys));
            }
            switch (ch.prop)
            {
                case "rot": Set(typeof(Transform), "localEulerAnglesRaw.z", 0); break;
                case "posX": Set(typeof(Transform), "m_LocalPosition.x", rest[target].x); break;
                case "posY": Set(typeof(Transform), "m_LocalPosition.y", rest[target].y); break;
                case "scale": Set(typeof(Transform), "m_LocalScale.x", 0); Set(typeof(Transform), "m_LocalScale.y", 0); break;
                case "alpha": Set(typeof(SpriteRenderer), "m_Color.a", 0); break;
                default: throw new Exception("Unknown property " + ch.prop);
            }
        }
        var settings = AnimationUtility.GetAnimationClipSettings(clip);
        settings.loopTime = data.loop;
        settings.stopTime = data.length;
        AnimationUtility.SetAnimationClipSettings(clip, settings);
        AssetDatabase.CreateAsset(clip, path);
        return clip;
    }

    static AnimatorController MakeController(AnimationClip idle, AnimationClip attack)
    {
        string path = Root + "/Animation/EstelleV12.controller";
        AssetDatabase.DeleteAsset(path);
        var controller = AnimatorController.CreateAnimatorControllerAtPath(path);
        controller.AddParameter("Attack", AnimatorControllerParameterType.Trigger);
        var machine = controller.layers[0].stateMachine;
        var idleState = machine.AddState("Idle"); idleState.motion = idle;
        var attackState = machine.AddState("Attack"); attackState.motion = attack;
        machine.defaultState = idleState;
        var enter = idleState.AddTransition(attackState);
        enter.hasExitTime = false; enter.duration = .06f; enter.hasFixedDuration = true;
        enter.AddCondition(AnimatorConditionMode.If, 0, "Attack");
        var exit = attackState.AddTransition(idleState);
        exit.hasExitTime = true; exit.exitTime = .92f; exit.duration = .15f; exit.hasFixedDuration = true;
        return controller;
    }

    static void MakeScene(GameObject prefab)
    {
        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        var cameraObject = new GameObject("Main Camera"); cameraObject.tag = "MainCamera";
        var camera = cameraObject.AddComponent<Camera>();
        camera.orthographic = true; camera.orthographicSize = 3.6f;
        camera.backgroundColor = new Color(.035f, .045f, .095f);
        camera.clearFlags = CameraClearFlags.SolidColor;
        cameraObject.transform.position = new Vector3(0, 2.95f, -10);
        var right = (GameObject)PrefabUtility.InstantiatePrefab(prefab, scene);
        right.name = "EstelleV12_FacingRight"; right.transform.position = new Vector3(2.8f, 0, 0);
        var left = (GameObject)PrefabUtility.InstantiatePrefab(prefab, scene);
        left.name = "EstelleV12_FacingLeft"; left.transform.position = new Vector3(-2.8f, 0, 0);
        left.transform.localScale = new Vector3(-1, 1, 1);
        var driver = new GameObject("Attack Preview Driver").AddComponent<EstelleV12Driver>();
        driver.rightAnimator = right.GetComponent<Animator>();
        driver.leftAnimator = left.GetComponent<Animator>();
        EditorSceneManager.SaveScene(scene, ScenePath);
        var scenes = EditorBuildSettings.scenes.Where(s => s.path != ScenePath).ToList();
        scenes.Insert(0, new EditorBuildSettingsScene(ScenePath, true));
        EditorBuildSettings.scenes = scenes.ToArray();
    }

    static void Validate(GameObject prefab)
    {
        var renderers = prefab.GetComponentsInChildren<SpriteRenderer>(true);
        var skins = prefab.GetComponentsInChildren<SpriteSkin>(true);
        if (renderers.Length != rig.parts.Length + 1 || skins.Length != rig.parts.Count(p => p.bones != null && p.bones.Length > 0))
            throw new Exception("Incorrect rig part counts: sprites=" + renderers.Length + " skins=" + skins.Length);
        foreach (var skin in skins)
        {
            var sprite = skin.GetComponent<SpriteRenderer>().sprite;
            if (skin.rootBone == null || skin.boneTransforms.Length != sprite.GetBones().Length || skin.boneTransforms.Any(t => t == null))
                throw new Exception("Unbound Sprite Skin: " + skin.name);
        }
        File.WriteAllText(Root + "/validation.txt",
            "Unity " + Application.unityVersion + "; 2D Animation 13.0.2\n" +
            "renderers=" + renderers.Length + " (" + string.Join(", ", renderers.Select(r => r.name)) + ")\n" +
            "SpriteSkin=" + skins.Length + " (" + string.Join(", ", skins.Select(s => s.name + ":" + s.boneTransforms.Length + " bones")) + ")\n" +
            PrefabPath + "\n" + ScenePath + "\n");
        Debug.Log("ESTELLE_V12_VALIDATION renderers=" + renderers.Length + " skins=" + skins.Length);
    }

    [MenuItem("Estelle V12/Export Package")]
    public static void Export()
    {
        string output = Path.GetFullPath("../../references/8_results/v012");
        Directory.CreateDirectory(output);
        string package = Path.Combine(output, "EstelleV12.unitypackage");
        AssetDatabase.ExportPackage(new[] { Root }, package, ExportPackageOptions.Recurse);
        Debug.Log("ESTELLE_V12_EXPORT_SUCCESS " + package);
    }
}
